import React, { useState } from 'react';
import { PieChart as PieIcon, Cpu, Award } from 'lucide-react';

interface ProbabilityPieProps {
  probabilities: {
    buy: number;
    hold: number;
    sell: number;
  };
  metrics?: {
    accuracy: number;
    precision: number;
    recall: number;
    f1: number;
    cv_folds: number;
    samples_trained: number;
  };
}

export const ProbabilityPie: React.FC<ProbabilityPieProps> = ({ probabilities, metrics }) => {
  const [hoveredSlice, setHoveredSlice] = useState<string | null>(null);

  const { buy, hold, sell } = probabilities;
  const total = buy + hold + sell || 100;

  // Normalized percentages
  const pctBuy = (buy / total) * 100;
  const pctHold = (hold / total) * 100;
  const pctSell = (sell / total) * 100;

  // SVG Donut calculation
  const radius = 80;
  const circumference = 2 * Math.PI * radius;

  const buyStroke = (pctBuy / 100) * circumference;
  const holdStroke = (pctHold / 100) * circumference;
  const sellStroke = (pctSell / 100) * circumference;

  const buyOffset = 0;
  const holdOffset = -buyStroke;
  const sellOffset = -(buyStroke + holdStroke);

  return (
    <div className="glass-panel p-6 sm:p-9 rounded-[36px] flex flex-col justify-between h-full relative overflow-hidden border border-white/10 shadow-2xl">
      {/* Header */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <PieIcon className="w-5 h-5 text-[#c9b896]" />
            <h3 className="text-xl font-bold font-mono tracking-tight text-white uppercase text-sm">
              ML Probability Distribution
            </h3>
          </div>
          <span className="text-xs font-mono px-3 py-1 rounded-full bg-white/10 text-white/80 border border-white/10">
            Softmax Ensemble
          </span>
        </div>
        <p className="text-xs text-white/50 mb-6 leading-relaxed">
          Forward 6-hour prediction probability mass split generated by Voting Classifier (Gradient Boosting + Random Forest).
        </p>
      </div>

      {/* Donut Chart Visual (Matching Screenshot 1) */}
      <div className="relative flex items-center justify-center my-4">
        <svg width="220" height="220" viewBox="0 0 220 220" className="transform -rotate-90">
          {/* Background circle track */}
          <circle
            cx="110"
            cy="110"
            r={radius}
            fill="transparent"
            stroke="rgba(255, 255, 255, 0.05)"
            strokeWidth="28"
          />

          {/* Buy Arc (Sage/Emerald) */}
          <circle
            cx="110"
            cy="110"
            r={radius}
            fill="transparent"
            stroke="#6a9a78"
            strokeWidth={hoveredSlice === 'buy' ? 34 : 28}
            strokeDasharray={`${buyStroke} ${circumference}`}
            strokeDashoffset={buyOffset}
            className="transition-all duration-500 cursor-pointer drop-shadow-[0_0_8px_rgba(106,154,120,0.25)]"
            onMouseEnter={() => setHoveredSlice('buy')}
            onMouseLeave={() => setHoveredSlice(null)}
          />

          {/* Hold Arc (Warm Lantern Amber) */}
          <circle
            cx="110"
            cy="110"
            r={radius}
            fill="transparent"
            stroke="#a89068"
            strokeWidth={hoveredSlice === 'hold' ? 34 : 28}
            strokeDasharray={`${holdStroke} ${circumference}`}
            strokeDashoffset={holdOffset}
            className="transition-all duration-500 cursor-pointer drop-shadow-[0_0_8px_rgba(168,144,104,0.25)]"
            onMouseEnter={() => setHoveredSlice('hold')}
            onMouseLeave={() => setHoveredSlice(null)}
          />

          {/* Sell Arc (Vintage Terracotta Rose) */}
          <circle
            cx="110"
            cy="110"
            r={radius}
            fill="transparent"
            stroke="#b87175"
            strokeWidth={hoveredSlice === 'sell' ? 34 : 28}
            strokeDasharray={`${sellStroke} ${circumference}`}
            strokeDashoffset={sellOffset}
            className="transition-all duration-500 cursor-pointer drop-shadow-[0_0_8px_rgba(184,113,117,0.25)]"
            onMouseEnter={() => setHoveredSlice('sell')}
            onMouseLeave={() => setHoveredSlice(null)}
          />
        </svg>

        {/* Center Cutout Stats */}
        <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
          <span className="text-[11px] font-mono text-white/50 uppercase tracking-widest">
            {hoveredSlice ? hoveredSlice.toUpperCase() : 'DOMINANT'}
          </span>
          <span className="text-3xl font-mono font-bold text-white tracking-tight">
            {hoveredSlice === 'buy' ? `${buy}%` : hoveredSlice === 'sell' ? `${sell}%` : hoveredSlice === 'hold' ? `${hold}%` : `${Math.max(buy, hold, sell)}%`}
          </span>
          <span className="text-[10px] text-[#c9b896]/70 font-mono tracking-wider">
            {hoveredSlice === 'buy' ? 'LONG PROBABILITY' : hoveredSlice === 'sell' ? 'SHORT PROBABILITY' : hoveredSlice === 'hold' ? 'NEUTRAL PROBABILITY' : 'ODDS CONFIDENCE'}
          </span>
        </div>
      </div>

      {/* Legend & Probability Bars */}
      <div className="space-y-3 mt-4">
        {/* Buy */}
        <div 
          onMouseEnter={() => setHoveredSlice('buy')}
          onMouseLeave={() => setHoveredSlice(null)}
          className={`p-3.5 rounded-2xl border transition-all cursor-pointer ${
            hoveredSlice === 'buy' ? 'bg-[#4a6e4a]/15 border-[#4a6e4a]/40' : 'bg-white/5 border-white/10'
          }`}
        >
          <div className="flex items-center justify-between text-xs font-mono mb-1.5">
            <span className="flex items-center gap-2 text-white">
              <span className="w-2.5 h-2.5 rounded-full bg-[#8fae8b]" />
              BUY Probability
            </span>
            <span className="text-[#8fae8b] font-bold">{buy}%</span>
          </div>
          <div className="w-full h-1.5 rounded-full bg-white/10 overflow-hidden">
            <div className="h-full bg-[#8fae8b] rounded-full transition-all duration-700" style={{ width: `${buy}%` }} />
          </div>
        </div>

        {/* Hold */}
        <div 
          onMouseEnter={() => setHoveredSlice('hold')}
          onMouseLeave={() => setHoveredSlice(null)}
          className={`p-3.5 rounded-2xl border transition-all cursor-pointer ${
            hoveredSlice === 'hold' ? 'bg-[#8a7040]/15 border-[#8a7040]/40' : 'bg-white/5 border-white/10'
          }`}
        >
          <div className="flex items-center justify-between text-xs font-mono mb-1.5">
            <span className="flex items-center gap-2 text-white">
              <span className="w-2.5 h-2.5 rounded-full bg-[#a89068]" />
              HOLD Probability
            </span>
            <span className="text-[#c9b896] font-bold">{hold}%</span>
          </div>
          <div className="w-full h-1.5 rounded-full bg-white/10 overflow-hidden">
            <div className="h-full bg-[#a89068] rounded-full transition-all duration-700" style={{ width: `${hold}%` }} />
          </div>
        </div>

        {/* Sell */}
        <div 
          onMouseEnter={() => setHoveredSlice('sell')}
          onMouseLeave={() => setHoveredSlice(null)}
          className={`p-3.5 rounded-2xl border transition-all cursor-pointer ${
            hoveredSlice === 'sell' ? 'bg-[#5a2a2e]/15 border-[#5a2a2e]/40' : 'bg-white/5 border-white/10'
          }`}
        >
          <div className="flex items-center justify-between text-xs font-mono mb-1.5">
            <span className="flex items-center gap-2 text-white">
              <span className="w-2.5 h-2.5 rounded-full bg-[#b87175]" />
              SELL Probability
            </span>
            <span className="text-[#c4868a] font-bold">{sell}%</span>
          </div>
          <div className="w-full h-1.5 rounded-full bg-white/10 overflow-hidden">
            <div className="h-full bg-[#b87175] rounded-full transition-all duration-700" style={{ width: `${sell}%` }} />
          </div>
        </div>
      </div>

      {/* Model Cross Validation Footnote */}
      {metrics && (
        <div className="mt-6 pt-4 border-t border-white/10 flex items-center justify-between text-[11px] font-mono text-white/50">
          <div className="flex items-center gap-1.5">
            <Award className="w-3.5 h-3.5 text-[#c9b896]" />
            <span>F1-Score: {metrics.f1}%</span>
          </div>
          <div className="flex items-center gap-1.5">
            <Cpu className="w-3.5 h-3.5 text-white/70" />
            <span>{metrics.samples_trained} historical candles</span>
          </div>
        </div>
      )}
    </div>
  );
};
